export const COMPTIA_OBJECTIVES: Record<string, string[]> = {
  'CompTIA A+ Core 1 — Domain 1.0 (Mobile Devices)': [
    '1.1 Laptop Hardware',
    '1.2 Mobile Displays',
    '1.3 Accessories & Ports',
    '1.4 Network Connectivity',
  ],
  'CompTIA A+ Core 1 — Domain 2.0 (Networking)': [
    '2.1 Ports & Protocols',
    '2.2 Network Equipment',
    '2.3 Wireless Protocols',
    '2.4 Network Services',
    '2.5 IP Addressing',
    '2.6 SOHO Networks',
    '2.7 Network Configs',
  ],
  'CompTIA A+ Core 1 — Domain 3.0 (Hardware)': [
    '3.1 Cables & Connectors',
    '3.2 RAM',
    '3.3 Storage Devices',
    '3.4 Motherboards & CPUs',
    '3.5 Power Supplies',
    '3.6 Custom PC Configurations',
    '3.7 Printers',
  ],
  'CompTIA A+ Core 1 — Domain 4.0 (Cloud)': [
    '4.1 Cloud Computing Concepts',
    '4.2 Client-Side Virtualization',
  ],
  'CompTIA A+ Core 1 — Domain 5.0 (Troubleshooting)': [
    '5.1 Troubleshooting Methodology',
    '5.2 Motherboard/RAM/CPU Issues',
    '5.3 Storage Issues',
    '5.4 Video/Display Issues',
    '5.5 Mobile Device Issues',
    '5.6 Printer Issues',
    '5.7 Network Issues',
  ],
  'CompTIA A+ Core 2 — Domain 1.0 (Operating Systems)': [
    '1.1 Windows Editions',
    '1.2 Command-Line Tools',
    '1.3 Windows 10 Features',
    '1.4 Control Panel Utilities',
    '1.5 Windows Settings',
    '1.6 Windows Networking',
    '1.7 App Installation/Config',
    '1.8 OS Types & Purposes',
    '1.9 OS Installations/Upgrades',
    '1.10 macOS Features/Tools',
    '1.11 Linux Features/Tools',
  ],
  'CompTIA A+ Core 2 — Domain 2.0 (Security)': [
    '2.1 Security Measures',
    '2.2 Wireless Security',
    '2.3 Malware Detection',
    '2.4 Social Engineering',
    '2.5 Windows Security Settings',
    '2.6 Workstation Security',
    '2.7 Mobile Device Security',
    '2.8 Data Destruction',
    '2.9 SOHO Network Security',
    '2.10 Browser Security',
  ],
  'CompTIA A+ Core 2 — Domain 3.0 (Software Troubleshooting)': [
    '3.1 Windows OS Issues',
    '3.2 PC Security Issues',
    '3.3 Malware Removal Best Practices',
    '3.4 Mobile OS/App Issues',
    '3.5 Mobile Security Issues',
  ],
  'CompTIA A+ Core 2 — Domain 4.0 (Operational Procedures)': [
    '4.1 IT Documentation',
    '4.2 Change Management',
    '4.3 Disaster Recovery',
    '4.4 Safety Procedures',
    '4.5 Environmental Impacts',
    '4.6 Privacy & Licensing',
    '4.7 Professionalism & Comms',
    '4.8 Scripting Basics',
    '4.9 Remote Access Tech',
  ],
  'Advanced Healthcare IT — EHR Architecture': [
    'EHR Integrations & Sandboxes', 'Data Interoperability (HL7/FHIR)', 'Database Management', 'System Downtime Procedures',
  ],
  'Advanced Healthcare IT — HIPAA Data Security': [
    'PHI Protection Strategies', 'Access Controls & Auditing', 'Threat Detection & Response', 'Compliance Documentation',
  ],
  'Advanced Healthcare IT — Clinical Workflows': [
    'Patient Admission to Discharge', 'Order Entry Systems (CPOE)', 'Telehealth Integrations', 'Medical IoT Troubleshooting',
  ],
};
