export const COMPTIA_OBJECTIVES: Record<string, string[]> = {
  'CompTIA A+ Core 1 — Domain 1.0 (Mobile Devices)': [
    '1.1 Laptop Hardware',
    '1.2 Mobile Displays',
    '1.3 Accessories & Ports',
    '1.4 Network Connectivity',
  ],
  'CompTIA A+ Core 1 — Domain 2.0 (Networking)': [
    '2.1 Ports & Protocols',
    '2.2 Network Equipment',
    '2.3 Wireless Protocols',
    '2.4 Network Services',
    '2.5 IP Addressing',
    '2.6 SOHO Networks',
    '2.7 Network Configs',
  ],
  'CompTIA A+ Core 1 — Domain 3.0 (Hardware)': [
    '3.1 Cables & Connectors',
    '3.2 RAM',
    '3.3 Storage Devices',
    '3.4 Motherboards & CPUs',
    '3.5 Power Supplies',
    '3.6 Custom PC Configurations',
    '3.7 Printers',
  ],
  'CompTIA A+ Core 1 — Domain 4.0 (Virtualization & Cloud)': [
    '4.1 Cloud Computing Concepts',
    '4.2 Client-Side Virtualization',
  ],
  'CompTIA A+ Core 1 — Domain 5.0 (HW & Network Troubleshooting)': [
    '5.1 Troubleshooting Methodology',
    '5.2 Motherboard/RAM/CPU Issues',
    '5.3 Storage Issues',
    '5.4 Video/Display Issues',
    '5.5 Mobile Device Issues',
    '5.6 Printer Issues',
    '5.7 Network Issues',
  ],
  'CompTIA A+ Core 2 — Domain 1.0 (Operating Systems)': [],
  'CompTIA A+ Core 2 — Domain 2.0 (Security)': [],
  'CompTIA A+ Core 2 — Domain 3.0 (Software Troubleshooting)': [],
  'CompTIA A+ Core 2 — Domain 4.0 (Operational Procedures)': [],
  'Advanced Healthcare IT — EHR Architecture': [],
  'Advanced Healthcare IT — HIPAA Data Security': [],
  'Advanced Healthcare IT — Clinical Workflows': [],
};
